[project]
name = "bita"
version = "0.1.0"
description = "A simple Python library for creating IIIF Presentation API manifests"
readme = "README.md"
authors = [{ name = "ysdmsnr" }]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "twine>=7.0.0",
]
